-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbp9YDfdxinuOfor/
VEd+oGm30yvlqaYJa1QEmhlD1zWgCgYIKoZIzj0DAQehRANCAAQD85oDDsgUA3J9
Q/ENMjIbexm/9QwP5kxAK/TLoRqTRG42V5CGaOjzHZt4yrccsjQYPDqp9ac6XXUi
B+o5Gqzw
-----END PRIVATE KEY-----